<a href="https://colab.research.google.com/github/Prerna99-star/Bank-Turnover-detector/blob/master/improvedANN_pyib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
#Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:, 13].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)
X = X[: , 1:]
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size =0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
Sc_X = StandardScaler() 
X_train = Sc_X.fit_transform(X_train)
X_test = Sc_X.transform(X_test)


In [0]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers import Dropout

classifier = Sequential()

classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu',
                     input_dim = 11))
classifier.add(Dropout(p = 0.1 ))

classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu'))
classifier.add(Dropout(p = 0.1 ))

classifier.add(Dense(output_dim = 1,
                     init = 'uniform', 
                     activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`


In [0]:
#fitting the ANN to the training set
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 100)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4869 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4360 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4337 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4295 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4303 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 109us/step - loss: 0.4260 - accuracy: 0.8159
Epoch 7/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4253 - accuracy: 0.8225
Epoch 8/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4243 - accuracy: 0.8261
Epoch 9/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.4288 - accuracy: 0.8267
Epoch 10/100
8000/8000 [==============================]

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [0]:
# Making the confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[1527   68]
 [ 241  164]]


In [0]:
# Evaluating ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers.core import Dense
def build_classifier():
  classifier = Sequential()

  classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu',
                     input_dim = 11))

  classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu'))

  classifier.add(Dense(output_dim = 1,
                     init = 'uniform', 
                     activation = 'sigmoid'))

  classifier.compile(optimizer = 'adam',
                     loss = 'binary_crossentropy',
                     metrics = ['accuracy'])
  return classifier

classifier = KerasClassifier(build_fn= build_classifier, batch_size = 10,  nb_epoch = 100 )
accuracies = cross_val_score(estimator= classifier, X = X_train, y = Y_train, cv = 10, n_jobs= -1)
print(accuracies)

[0.78625    0.79000002 0.80000001 0.78250003 0.81625003 0.81
 0.82125002 0.79374999 0.79874998 0.79500002]


In [26]:

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers.core import Dense
def build_classifier(optimizer):
  classifier = Sequential()

  classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu',
                     input_dim = 11))

  classifier.add(Dense(output_dim = 6,
                     init = 'uniform', 
                     activation = 'relu'))

  classifier.add(Dense(output_dim = 1,
                     init = 'uniform', 
                     activation = 'sigmoid'))

  classifier.compile(optimizer = optimizer,
                     loss = 'binary_crossentropy',
                     metrics = ['accuracy'])
  return classifier

classifier = KerasClassifier(build_fn= build_classifier)
parameters = {'batch_size': [25, 32],
              'nb_epoch': [100, 500],
              'optimizer':['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
print(best_accuracy)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`


Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5507 - accuracy: 0.7971
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5679 - accuracy: 0.7962
Epoch 1/1
7200/7200 [==============================] - 0s 55us/step - loss: 0.5666 - accuracy: 0.7953
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5505 - accuracy: 0.7961
Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.5791 - accuracy: 0.7911
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5787 - accuracy: 0.7926
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5520 - accuracy: 0.7950
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5498 - accuracy: 0.7962
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5628 - accuracy: 0.7949
Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5708